# Generated by Django 5.1.1 on 2025-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('الشحن', 'الشحن'), ('التخليص الجمركي', 'التخليص الجمركي')], max_length=50)),
                ('shipment_type', models.CharField(blank=True, choices=[('وثائق', 'وثائق'), ('طرود', 'طرود'), ('بضائع', 'بضائع')], max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_description', models.TextField(blank=True, null=True)),
                ('customs_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
