# Generated by Django 5.1.1 on 2025-03-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
